apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
spec:
  containers:
  - image: busybox
    name: empty-dir
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /empty
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}