apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

## Replace name 
patches:
  - target: 
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: replace
        path: /metadata/name
        value: mynginx

## Replace replicas 
patches:
  - target:
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
