apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

## Replace name 
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target: 
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: replace
        path: /metadata/name
        value: mynginx

## Replace replicas 
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

## Add label
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: add
        path: /metadata/labels/env
        value: dev

## Remove label 
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml



patches:
  - target:
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: remove
        path: /metadata/labels/org
