apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx.yaml

    ## json approach to replace replicas 
patches:
  - target:
      kind: Deployment
      name: nginx-deployment

    patch: |-
      - op: add
        path: /metadata/labels/env
        value: dev

#  kubectl   kustomize . 